### PR TITLE
Add a host alias for detached steps

### PR DESCRIPTION
**Pull request by hhomar**
This allows detached steps to be referenced by other steps as per
services.

### CODE REVIEW

**Comment by marko-gacesa** [comment]
@hhomar what was the concrete example you needed this for?

**Comment by bradrydzewski** [comment]
@marko-gacesa I think I understand this pull request.  Currently we have the ability to define services and then communicate with those services using a hostname: https://docs.drone.io/pipeline/kubernetes/syntax/services/

this pull request look like it ensures this works for detached servers (services defined in the steps section). See https://docs.drone.io/pipeline/kubernetes/syntax/services/#detached-steps

**Comment by hhomar** [comment]
Hi. Sorry, I should have been more clear in the pull request, but you're exactly right.

This was how it worked when I was using the docker pipeline.

**Comment by mshebeko-twist** [comment]
Hi, do we have an estimate of this PR being merged? 
Pipelines that worked with docker pipelines stopped working for me.

Another thing is - it maybe easier to propagate step name to container name inside pod this way kubernetes will know how to route packets between containers.

**Review by tphoney — APPROVED** [review]

**Comment by tphoney** [comment]
thanks for the work @hhomar

**Pull request merged**
