### PR TITLE
feat: support host_aliases

### PR DESCRIPTION
**Pull request by ysicing**
Signed-off-by: ysicing <i@ysicing.me>

## support pipeline hosts

```yaml
host_aliases:
  - ip: 1.1.1.1.1
    hostnames: 
      - www.baidu.com
```

### CODE REVIEW

**Comment by tphoney** [comment]
is #52 comparable to this ?

**Comment by ysicing** [comment]
@tphoney  No, this supports the definition of HostAliases in pipeline

**Comment by ysicing** [comment]
@tphoney Hey, the document has been updated.

**Comment by tphoney** [comment]
Docs merged and PR merged. 
Great work @ysicing i owe you a 🍺

**Pull request merged**
