### PR TITLE
Fix logs

### PR DESCRIPTION
**Pull request by sethpollack**
With `io.Copy` my logs had a bunch of extra newlines all over the place, and was sometimes missing lines. With `bufio.NewReader` the logs look good.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
Interesting. Does this mean we can remove the following from the runner library, which we implemented for Kubernetes?
https://github.com/drone/runner-go/blob/master/livelog/livelog.go#L182:L196

**Comment by sethpollack** [comment]
I'm not sure. I was just looking at different tools to see they handled it and looked like this is what kubectl uses https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/logs/logs.go#L402

**Comment by bradrydzewski** [comment]
cool, I will try and run some tests and see.  It would be great to be able to remove the split function, which is not required by the Docker runner.  If this works, we may also want to move to a helper function in runner-go since we also have some issues with logs in the exec and ssh runners.

**Comment by sethpollack** [comment]
Ok cool thanks!

**Comment by bradrydzewski** [comment]
I'm good merging, but I wanted to move this code to the runner-go package since I think we can use it to fix some issues with the other runners related to newlines:
https://godoc.org/github.com/drone/runner-go/livelog#Copy

**Comment by bradrydzewski** [comment]
also any chance you could dump some kubernetes logs that we could add as a unit test to the `Copy` function?  I will gather similar output for other runner types (exec, ssh).

**Comment by sethpollack** [comment]
Ok, I updated the PR to use `livelog.Copy`. Not sure having k8s logs would help. I think the issue is that it writes partial lines or multiple lines depending on when the buffer is full.

**Comment by sethpollack** [comment]
Ok, I updated the PR to use `livelog.Copy`. Not sure having k8s logs would help. I think the issue is that it writes partial lines or multiple lines depending on when the buffer is full.

**Pull request merged**
