### PR TITLE
WIP: Add a custom privileged images flag

### PR DESCRIPTION
**Pull request by KashifSaadat**
Following on from this discussion: https://discourse.drone.io/t/failing-to-run-dind-in-a-kubernetes-pipeline/7283/3

### CODE REVIEW

**Comment by KashifSaadat** [comment]
This is currently not functional. I noticed when moving into the `isPrivileged` check, there is nothing to iterate on so it seems the `PrivilegedPlugins` and `PrivilegedImages` are not being set correctly. Stepped through the code and couldn't find the cause, probably missing something obvious here!

**Comment by tboerger** [comment]
The privileged images shouldn't be split into two different variables. Both are simply docker images.

**Comment by bradrydzewski** [comment]
> ^ Figured out what was happening. I was testing a privileged Service rather than a Step, so the isPrivileged() check wasn't being applied. I've now added this in and it works.
> With this small change, it also means my original use-case would succeed without renaming and creating a new environment variable.

thanks for the alternate fix.  I pushed https://github.com/drone-runners/drone-runner-kube/commit/c4bfe0a0d8483a6b59c61ec6517896cb36131ef2 which adds this check to service containers. I'm thinking, if you don't mind, that we just leave the logic as-is for now. We can always add more logic in the future if needed. Sound good?

**Comment by KashifSaadat** [comment]
Yep no problem that's just what I needed, thanks! I'll close this PR.

**Pull request closed without merging**
